### ISSUE TITLE
Add "BIGROLL" functionality for controlled re-rolls of history events

### ISSUE THREAD

**Issue by ghost** [ericearlpdx/MakeRPG#16]
In cases like:

```
Age:
    dice: 1d6 + 16
    roll:
        17:
            next: Life
        18:
            next: <ROLL X2> Life
        19:
            next: <ROLL X3> Life
        20:
            next: <ROLL X4> Life
        21:
            next: <ROLL X5> Life
        22:
            next: <ROLL X6> Life
    next: Siblings
```

This could have been captured with something more like:

```
Age:
    dice: 1d6 + 16
    roll:
        17-22:
            next: <BIGROLL 1-6> Life
    next: Siblings
```

Which implies a case like "for any roll of the `1d6 + 16`, whatever the `next` is should be rerolled that many times".

This could further be generalized for extra big rolls to something like:

```
Age:
    dice: 1d300
    roll:
        1-300:
            next: <BIGROLL 1-300/20> Life
    next: Siblings
```

Which implies a case like "for any roll of the `1d300`, whatever the `next` is should be rolled `roll`/20 rounded up".  So a `roll` of 70 would trigger 4 rolls (70/20=3.5, rounded up to 4).
