### ISSUE TITLE
Support multiplication and differing dice addition in stat or skill "set"

### ISSUE THREAD

**Issue by ericearl** [ericearlpdx/MakeRPG#24]
Should be able to support more complex dice outcome multiplication and differing dice-to-dice addition.  Like this example:

```yaml
stats:
    STRENGTH:
        set: ( 3d6 * 100 ) + 1d100
```

In this case, a roll of 3d6 would be rolled, whose outcome would be multiplied by 100, then 1d100 would be rolled and added on top of the rolled and multiplied outcome.
