### ISSUE TITLE
Support roll and stat in skill purchase

### ISSUE THREAD

**Issue by ericearl** [ericearlpdx/MakeRPG#25]
Allow the result of a skill purchase to be a roll.  Also support basic addition and subtraction of a stat with that roll.

Example:

```yaml
skills:
    Accounting:
        cost: 3
        purchase: 1d8 + stat
        stat: INTELLIGENCE
```
