### ISSUE TITLE
Support prereq mini-language

### ISSUE THREAD

**Issue by ericearl** [ericearlpdx/MakeRPG#26]
Support a mini prerequisite logical language.  Pull `prereq`s from skills or stats by name and allow >, <, >=, <=, ==, AND, and OR operations.

Example:

```yaml
skills:
    Accounting:
        prereq: skills|Mathematics <= 85
```
