### ISSUE TITLE
Support stat mini-language in skill purchasing

### ISSUE THREAD

**Issue by ericearl** [ericearlpdx/MakeRPG#27]
Support stat mini-language in skill purchasing.  Operators like min() and max().

 Example:

```yaml
skills:
    Administration:
        set: 100 - stat
        cost: 5
        purchase: 1d6 + stat
        stat: min(INTELLIGENCE|WISDOM|CHARISMA)
```
